<?php

/*
	swCV client.php file
	Hppsrc 2026
	Based on version 0.1.0-alpha
	? General MySQL PDO client
*/

mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);

$_swCV_conn = null;
$_swCV_db_host = get_env("host");
$_swCV_db_user = get_env("user");
$_swCV_db_pass = get_env("pass");
$_swCV_db_name = get_env("name");
$_swCV_db_gen_error = get_env("sql_generic_error");
$_swCV_db_gen_error_msg = get_env("sql_generic_error_msg");

// ! IA GENERATED by Gemini 3.6 medium
function client_get_caller_location(): string
{
	$trace = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS, 10);
	foreach ($trace as $step) {
		if (isset($step['file']) && basename($step['file']) !== 'client.php') {
			$file = basename($step['file']);
			$line = $step['line'] ?? '?';
			$func = isset($step['function']) ? $step['function'] . '()' : 'script';
			return "$file:$line on $func";
		}
	}
	return "unknown:?";
}

function client_create_conn()
{
	try {
		global $_swCV_db_host, $_swCV_db_user, $_swCV_db_pass, $_swCV_db_name, $_swCV_conn;
		$_swCV_conn = mysqli_connect($_swCV_db_host, $_swCV_db_user, $_swCV_db_pass, $_swCV_db_name);
		return $_swCV_conn;
	} catch (mysqli_sql_exception $e) {
		throw new Exception(client_get_error($e), 1);
	}
}

function client_get_conn()
{
	try {
		global $_swCV_conn;
		if (!$_swCV_conn) {
			client_create_conn();
		}
		return $_swCV_conn;
	} catch (mysqli_sql_exception $e) {
		throw new Exception(client_get_error($e), 1);
	}
}

function client_start_transaction($callback = null)
{
	try {
		$conn = client_get_conn();
		mysqli_begin_transaction($conn);
		if (is_callable($callback)) {
			$callback();
			mysqli_commit($conn);
		}
	} catch (mysqli_sql_exception $e) {
		mysqli_rollback($conn);
		throw new Exception(client_get_error($e), 1);
	}
}

function client_rollback()
{
	try {
		$conn = client_get_conn();
		mysqli_rollback($conn);
	} catch (mysqli_sql_exception $e) {
		throw new Exception(client_get_error($e), 1);
	}
}

function client_commit()
{
	try {
		$conn = client_get_conn();
		mysqli_commit($conn);
	} catch (mysqli_sql_exception $e) {
		throw new Exception(client_get_error($e), 1);
	}
}

function client_sql(string $query, array $params = [], string $types = ""): bool
{
	if (stripos(trim($query), 'select') === 0) {
		throw new Exception("ERROR: Prohibited use of SELECT queries in client_sql(). Please use client_select() instead. | Origen: " . client_get_caller_location(), 1);
	}

	try {
		$conn = client_get_conn();
		if (empty($params)) {
			return mysqli_query($conn, $query);
		}

		$stmt = mysqli_prepare($conn, $query);
		if ($stmt === false) {
			throw new Exception(mysqli_error($conn));
		}

		mysqli_stmt_bind_param($stmt, $types, ...$params);
		mysqli_stmt_execute($stmt);

		$result = mysqli_stmt_get_result($stmt);
		if ($result === false) {
			return true;
		}
		return $result;

	} catch (mysqli_sql_exception $e) {
		throw new Exception(client_get_error($e), 1);
	}
}

function client_select($query, array $params = [], string $types = "")
{
	try {
		$conn = client_get_conn();
		if (empty($params)) {
			$result = mysqli_query($conn, $query);
		} else {
			$stmt = mysqli_prepare($conn, $query);
			if ($stmt === false) {
				throw new Exception(mysqli_error($conn));
			}
			mysqli_stmt_bind_param($stmt, $types, ...$params);
			mysqli_stmt_execute($stmt);
			$result = mysqli_stmt_get_result($stmt);
		}

		if ($result === false) {
			return [];
		}
		return mysqli_fetch_all($result, MYSQLI_ASSOC);
	} catch (mysqli_sql_exception $e) {
		throw new Exception(client_get_error($e), 1);
	}
}

function client_disconn()
{
	global $_swCV_conn;
	if ($_swCV_conn) {
		mysqli_close($_swCV_conn);
		$_swCV_conn = null;
	}
}

function client_get_error($e = null)
{
	global $_swCV_conn, $_swCV_db_gen_error, $_swCV_db_gen_error_msg;

	$location = client_get_caller_location();

	if ($e instanceof mysqli_sql_exception) {

		$msg = $e->getMessage();

		// Overwrite for special cases
		switch ($e->getCode()) {

			case '2002':
				$msg = "No MySQL/MariaDB server running or found.";
				break;

			case '1044':
				$msg = "Database user doesn't have permission to access this database.";
				break;

			case '1049':
				$msg = "The database specified in your .env file doesn't exist. `swCV` expected. Does your db exists? Please open the <a href='installer/installer.html'>installer</a> view to set up everything if needed";
				break;

			case '1146':
				$msg = "Some important tables doesn't exist. Your instalation might be broken. Please open the <a href='installer/installer.html'>installer</a> view to set up everything if needed.";
				break;

			case '1045':
				$msg = "Access was denied. Check your MySQL/MariaDB username and password in the .env file.";
				break;

		}

		if ($_swCV_db_gen_error) {
			return "Error: " . $_swCV_db_gen_error_msg;
		} else {
			return "Error: " . $msg . "<br>Code: " . (int) $e->getCode() . "<br>File: " . $location;
		}
	}

	if (!$_swCV_conn) {
		return mysqli_connect_error();
	}
	return mysqli_error($_swCV_conn);
}
