<?php

/*
	swCV env_parser.php file
	Hppsrc 2026
	Based on version 0.1.0-alpha
	? env related functions
*/

// load .env and turn into $_ENV("KEY")
// * This function was AI generated by Gemini 3.5 flash, sorry :(
function load_env(): void
{
	if (!file_exists(".env")) {
		throw new Exception("CATASTROPHIC ERROR: Env file not found.");
	}

	$lines = file(".env", FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);

	if ($lines === false) {
		throw new Exception("CATASTROPHIC ERROR: Failed to read environment file.");
	}

	foreach ($lines as $line) {
		$line = trim($line);

		// Ignore comments and empty lines
		if (empty($line) || strpos($line, '#') === 0) {
			continue;
		}

		// Split by the first '=' sign
		if (strpos($line, '=') !== false) {
			list($key, $value) = explode('=', $line, 2);

			$key = trim($key);
			$value = trim($value);

			// Remove surrounding quotes from the key if they exist
			if (
				(str_starts_with($key, '"') && str_ends_with($key, '"')) ||
				(str_starts_with($key, "'") && str_ends_with($key, "'"))
			) {
				$key = substr($key, 1, -1);
			}

			// Remove surrounding quotes from the value if they exist
			if (
				(str_starts_with($value, '"') && str_ends_with($value, '"')) ||
				(str_starts_with($value, "'") && str_ends_with($value, "'"))
			) {
				$value = substr($value, 1, -1);
			}

			// Convert boolean and null strings to actual PHP types
			$lowerValue = strtolower($value);
			if ($lowerValue === 'true') {
				$value = true;
			} elseif ($lowerValue === 'false') {
				$value = false;
			} elseif ($lowerValue === 'null') {
				$value = null;
			}

			$_ENV[$key] = $value;

			// putenv only supports string values
			$envStringValue = is_bool($value) ? ($value ? 'true' : 'false') : (string) $value;
			putenv("{$key}={$envStringValue}");
		}
	}
}

// * Not AI generated, full Human Stupidity
// return key value from $_ENV, if not null
function get_env(string $k): string|null
{
	if (isset($_ENV[$k])) {
		return $_ENV[$k];
	} else {
		return null;
	}
}